# Generated by Django 4.0.4 on 2022-05-29 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0004_alter_bank_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, null=True)),
                ('payable_amount', models.IntegerField()),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='JapanSchoolPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_school', models.CharField(blank=True, max_length=50, null=True)),
                ('payable_amount', models.IntegerField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('paid_by', models.CharField(max_length=50)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.IntegerField(blank=True, default=0)),
                ('loan_amount', models.IntegerField(blank=True, default=0)),
                ('medical_expense', models.IntegerField(blank=True, default=0)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('paid_by', models.CharField(max_length=50)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('salary_paid_status', models.BooleanField(default=False)),
                ('loan_paid_status', models.BooleanField(default=False)),
                ('bonus_paid_status', models.BooleanField(default=False)),
                ('medicalExpense_paid_status', models.BooleanField(default=False)),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('payable_amount', models.IntegerField()),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_amount', models.IntegerField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('paid_by', models.CharField(max_length=50)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
    ]
