# Generated by Django 4.0.4 on 2022-06-09 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('employee', '0001_initial'),
        ('services', '0001_initial'),
        ('student', '0002_alter_student_age_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('person_name', models.CharField(max_length=50, null=True)),
                ('payable_amount', models.IntegerField()),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='JapanSchoolPayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('other_school', models.CharField(blank=True, max_length=50, null=True)),
                ('payable_amount', models.IntegerField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('salary_amount', models.IntegerField(blank=True, null=True)),
                ('bonus_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('loan_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('medical_expense', models.IntegerField(blank=True, default=0, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('salary_paid_status', models.BooleanField(default=False)),
                ('loan_paid_status', models.BooleanField(default=False)),
                ('bonus_paid_status', models.BooleanField(default=False)),
                ('medicalExpense_paid_status', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_by_employee', to='employee.employee')),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('payable_amount', models.IntegerField()),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payable_amount', models.IntegerField(blank=True, null=True)),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('agent_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.agent')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('payment_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
