# Generated by Django 4.0.4 on 2022-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountPayable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpayable',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companypayable',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeepayable',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='japanschoolpayable',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalpayable',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
    ]
