# Generated by Django 4.0.4 on 2022-06-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=50, null=True)),
                ('account_num', models.BigIntegerField()),
                ('amount_of_money', models.BigIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_from_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_category', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_to', models.CharField(blank=True, max_length=80, null=True)),
                ('paid_to_id', models.IntegerField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('received_by_id', models.IntegerField(blank=True, null=True)),
                ('amount_of_money', models.IntegerField(blank=True, null=True)),
                ('date_of_transaction', models.DateField(blank=True, null=True)),
                ('id_of_sector', models.CharField(blank=True, max_length=128, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
    ]
