# Generated by Django 4.0.4 on 2022-05-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=50, null=True)),
                ('account_num', models.BigIntegerField()),
                ('amount_of_money', models.BigIntegerField()),
            ],
        ),
    ]
