# Generated by Django 4.0.4 on 2022-05-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_from_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_of_money', models.IntegerField()),
                ('date_of_money_in', models.DateField(blank=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
    ]
