# Generated by Django 4.0.4 on 2022-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='amount_of_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
