# Generated by Django 4.0.4 on 2022-05-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_statement_amount_of_money'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['id']},
        ),
    ]
