# Generated by Django 4.0.4 on 2022-05-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bank_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='id_of_sector',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
