# Generated by Django 4.0.4 on 2022-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeRentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_cost', models.IntegerField()),
                ('date_of_payment', models.DateField(blank=True, null=True)),
                ('method_of_payment', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='OfficeRent',
            new_name='DocumentRenewalExpense',
        ),
    ]
