# Generated by Django 4.0.4 on 2022-05-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_statement'),
        ('expenses', '0002_officerentexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
        migrations.AddField(
            model_name='documentrenewalexpense',
            name='payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
        migrations.AddField(
            model_name='miscexpense',
            name='payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
        migrations.AddField(
            model_name='officerentexpense',
            name='payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
        migrations.AddField(
            model_name='utilityexpense',
            name='payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
    ]
