# Generated by Django 4.0.4 on 2022-05-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_dailyexpense_payment_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpense',
            name='method_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrenewalexpense',
            name='method_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='miscexpense',
            name='method_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='officerentexpense',
            name='method_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilityexpense',
            name='method_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20),
        ),
    ]
