# Generated by Django 4.0.4 on 2022-05-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_dailyexpense_method_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentrenewalexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miscexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officerentexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilityexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
