# Generated by Django 4.0.4 on 2022-06-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_officerentexpense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentrenewalexpense',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miscexpense',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officerentexpense',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilityexpense',
            name='connect_with_bank',
            field=models.BooleanField(default=False),
        ),
    ]
