# Generated by Django 4.0.4 on 2022-06-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_email', models.EmailField(max_length=50, null=True, unique=True)),
                ('agent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_phone', models.BigIntegerField()),
                ('agent_date_joined', models.DateField(blank=True, null=True)),
                ('agent_photo', models.ImageField(blank=True, null=True, upload_to='agents/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_role', models.CharField(max_length=80)),
                ('employee_email', models.EmailField(max_length=50, null=True, unique=True)),
                ('employee_salary', models.IntegerField()),
                ('employee_address', models.CharField(blank=True, max_length=100)),
                ('employee_phone', models.BigIntegerField()),
                ('employee_date_joined', models.DateField(blank=True, null=True)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
