# Generated by Django 4.0.4 on 2022-06-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=80)),
                ('book_price', models.CharField(blank=True, max_length=80, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('book_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='media/books/')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_address', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
