# Generated by Django 4.0.4 on 2022-06-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_educationalrecord_student_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=80)),
                ('book_price', models.CharField(blank=True, max_length=80, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('book_stock_quantity', models.IntegerField(blank=True, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='BookSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_quantity', models.IntegerField(blank=True, null=True)),
                ('sold_to_other', models.CharField(blank=True, max_length=80, null=True)),
                ('price_of_each', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(default=0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.book')),
                ('sold_to_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.DeleteModel(
            name='BookPurchase',
        ),
    ]
