# Generated by Django 4.0.4 on 2022-06-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_book_booksale_delete_bookpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksale',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
