# Generated by Django 4.0.4 on 2022-05-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('asset_price', models.IntegerField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('depreciation_percent', models.IntegerField()),
            ],
        ),
    ]
