# Generated by Django 4.0.4 on 2022-05-29 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_bank_options'),
        ('inventory', '0003_alter_asset_depreciation_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='method_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank Transfer')], default='NULL', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='payment_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
    ]
