# Generated by Django 4.0.4 on 2022-06-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField(unique=True)),
                ('father_name', models.CharField(max_length=50, null=True)),
                ('mother_name', models.CharField(max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='NULL', max_length=20)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('premanent_address', models.TextField(blank=True, null=True)),
                ('contact_number', models.BigIntegerField()),
                ('student_email', models.EmailField(max_length=50, unique=True)),
                ('date_of_registration', models.DateField(auto_now_add=True)),
                ('student_photo', models.ImageField(upload_to='students/')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('contact_number', models.BigIntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_category', models.CharField(max_length=30)),
                ('cgpa_or_gpa', models.FloatField(blank=True, null=True)),
                ('passing_year', models.DateField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
