# Generated by Django 4.0.4 on 2022-06-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_age_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalrecord',
            name='education_category',
        ),
        migrations.AddField(
            model_name='educationalrecord',
            name='HONOURS_DEGREE_FAZIL',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='educationalrecord',
            name='HSC_ALIM_DIPLOMA',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='educationalrecord',
            name='MASTERS_KAMIL',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='educationalrecord',
            name='SSC_DAKHIL',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
