# Generated by Django 4.0.4 on 2022-06-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_educationalrecord_education_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_educational_record', to='student.student'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencyContact', to='student.student'),
        ),
    ]
