# Generated by Django 4.0.5 on 2022-06-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_educationalrecord_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='HONOURS_DEGREE_FAZIL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='HSC_ALIM_DIPLOMA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='MASTERS_KAMIL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='SSC_DAKHIL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_person_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_person_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_person_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_person_occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_person_relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passing_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EducationalRecord',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
