# Generated by Django 4.0.4 on 2022-06-09 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('services', '0001_initial'),
        ('employee', '0001_initial'),
        ('student', '0002_alter_student_age_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_installment_amount', models.IntegerField(default=0, verbose_name='First Installment')),
                ('second_installment_amount', models.IntegerField(default=0, verbose_name='Second Installment')),
                ('third_installment_amount', models.IntegerField(default=0, verbose_name='Third Installment')),
                ('remaining_installment_amount', models.IntegerField(default=0, verbose_name='Remaining Amount')),
                ('total_fees', models.IntegerField()),
                ('date_of_receive', models.DateField(blank=True, null=True)),
                ('method_of_receive', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20, verbose_name='Received Through')),
                ('note', models.TextField(blank=True, null=True)),
                ('first_installment_is_receieved', models.BooleanField(default=False, verbose_name='1st Installment Paid')),
                ('second_installment_is_receieved', models.BooleanField(default=False, verbose_name='2nd Installment Paid')),
                ('third_installment_is_receieved', models.BooleanField(default=False, verbose_name='3rd Installment Paid')),
                ('first_installment_is_pending', models.BooleanField(default=False)),
                ('second_installment_is_pending', models.BooleanField(default=False)),
                ('third_installment_is_pending', models.BooleanField(default=False)),
                ('first_installment_is_rejected', models.BooleanField(default=False)),
                ('second_installment_is_rejected', models.BooleanField(default=False)),
                ('third_installment_is_rejected', models.BooleanField(default=False)),
                ('is_full_paid', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('received_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('person_name', models.CharField(max_length=50)),
                ('receivable_amount', models.IntegerField()),
                ('date_of_receive', models.DateField(blank=True, null=True)),
                ('method_of_receive', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('received_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JapanSchoolReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('receivable_amount', models.IntegerField()),
                ('date_of_receive', models.DateField(blank=True, null=True)),
                ('method_of_receive', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('received_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReceivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('receivable_amount', models.IntegerField()),
                ('date_of_receive', models.DateField(blank=True, null=True)),
                ('method_of_receive', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank_Transfer')], default='NULL', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('connect_with_bank', models.BooleanField(default=False)),
                ('received_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
