# Generated by Django 4.0.4 on 2022-06-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('accountReceivable', '0002_rename_is_pending_studentreceivable_first_installment_is_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='japanschoolreceivable',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='studentreceivable',
            name='is_full_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentreceivable',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
