# Generated by Django 4.0.4 on 2022-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountReceivable', '0004_alter_studentreceivable_first_installment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreceivable',
            name='first_installment_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='First Installment'),
        ),
        migrations.AlterField(
            model_name='studentreceivable',
            name='remaining_installment_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Remaining Amount'),
        ),
        migrations.AlterField(
            model_name='studentreceivable',
            name='second_installment_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Second Installment'),
        ),
        migrations.AlterField(
            model_name='studentreceivable',
            name='third_installment_amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Third Installment'),
        ),
    ]
