# Generated by Django 4.0.4 on 2022-06-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('accountReceivable', '0007_alter_studentreceivable_second_installment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='japanschoolreceivable',
            name='school_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.school'),
        ),
    ]
