# Generated by Django 4.0.4 on 2022-06-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountReceivable', '0008_japanschoolreceivable_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='japanschoolreceivable',
            old_name='school_name',
            new_name='school',
        ),
    ]
